config/routes.rb
Rails.application.routes.draw do
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  root 'posts#index'
  resources :posts, only: [ :new, :create, :show, :index]
end

app/models/post.rb
class Post < ActiveRecord::Base
  # Callbacks
  before_save :markdown

  # Validations
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true

  # Associations
  has_many :taggings
  has_many :tags, through: :taggings

  def tag_list
	tags = self.tags.collect do |tag|
	  tag.title
	end
	tags.to_a
  end

  def tag_list=(tags_string)
	tag_names = tags_string.split(',').collect { |t| t.strip.downcase }.uniq
	new_or_found_tags = tag_names.collect { |title| Tag.find_or_create_by(title: title) }
	self.tags = new_or_found_tags
  end

  protected
	def markdown
	  render_options = {
		filter_html:     true,
		hard_wrap:       true,
		link_attributes: { rel: 'nofollow' }
	  }
	  renderer = ApplicationHelper::HTML.new(render_options)

	  extensions = {
		autolink:           true,
		fenced_code_blocks: true,
		lax_spacing:        true,
		no_intra_emphasis:  true,
		strikethrough:      true,
		superscript:        true
	  }
	  self.body = Redcarpet::Markdown.new(renderer, extensions).render(self.body).html_safe
	end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :title, presence: true
  # Associations
  has_many :taggings
  has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # include SessionHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :require_login , only: [ :new , :create ]

  def new
	@post = Post.new
  end

  def create
	@post = Post.new(post_params)
	if @post.save
	  flash[:success] = "Post successfully created!"
	  redirect_to @post
	else
	  render :new
	end
  end

  def show
	@post = Post.find(params[:id])
  end

  def index
	@posts = Post.all
	@tags = Tag.all
  end


  private
	def post_params
	  params.require(:post).permit(:title, :body, :draft, :tag_list, :id)
	end

	def require_login
	  redirect_to root_url unless logged_in?(current_user)
	  true
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end

  def home
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTML < Redcarpet::Render::HTML
	include Rouge::Plugins::Redcarpet
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <div class="container">
	<p class="text-muted pull-left">
	  © <%= Time.now.year %> Matias Pan. All rights reserved.
	</p>
	<div class='pull-right'>
	  <p class='text-muted'>
		Find me on:
		<a href='#' class="foundation-github"></a>
		<a href='#' class="fc-webicon google"></a>
		<a href='#' class="fc-webicon twitter"></a>
		<a href='#' class="fc-webicon facebook"></a>
	  </p>
	</div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar>
	<ul class="title-area">
	  <li class="name">
		<h1><a class="logo show-for-small-only" href="#">Matias Pan</a></h1>
	  </li>
	  <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
	</ul>
	<section class="top-bar-section">
	  <div class="logo-wrapper hide-for-small-only">
		<div class="logo">
		  <img src="https://www.codementor.io/assets/tutorial_icon/ruby-on-rails.png">
		</div>
	  </div>
	  <!-- Right Nav Section -->
	  <ul class="right">
		<a href="<%= contact_path %>">
		  <button class="button primary radius">
			Contact
		  </button>
		</a>
		<div class="row">
		  <div class="small-6 columns block">
			<input type="text" placeholder="Search posts">
		  </div>
		  <button class="primary button radius" name="Go" value="Go">Go</button>
		</div>
	  </ul>
	  <!-- Left Nav Section -->
	  <ul class="left">
		<%# <li><a href="#">About</a></li> %>
		<a href="<%= about_path %>">
		  <button class="button primary radius">
			About
		  </button>
		</a>
	  </ul>
	</section>
  </nav>
</div><!-- /navigation -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Matias Pan" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

	<%= render 'layouts/header' %>

	<div class="sep-top">
	  <%= render "shared/flash" %>
	  <%= yield %>
	</div>

	<%= render 'layouts/footer' %>

  </body>
</html>

app/views/posts/_post.html.erb
<div class="panel radius">
  <div class="post-title">
	<h1>
	  <%= post.title %>
	</h1>
	<small class="really-small">
	  <span class='glyphicon glyphicon-time'></span> <%= post.created_at.strftime("%A, %d %b %Y %l:%M %p")%>.
	</small>
	<br />
	<small class="really-small">
	  <% post.tag_list.each do |tag_name| %>
		<code>
		  <%= tag_name %>
		</code>
	  <% end %>
	</small>
  </div>
  <br />
  <%=raw post.body %>
</div>

app/views/posts/_post_form.html.erb
<% if @post.errors.full_messages.any? %>
  <ul class="error_explanation">
	<% @post.errors.full_messages.each do |message, message_type| %>
	  <li>
		<div data-alert class="alert-box alert radius">
		  <%= message %>
		  <a href="#" class="close">&times;</a>
		</div>
	  </li>
	<% end %>
  </ul>
<% end %>
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :tag_list %>
  <%= f.text_field :tag_list, class: 'form-control' %>

  <%= f.label :body %>
  <%= f.text_area :body, class: 'form-control', rows: 50 %>


  <%= f.check_box :draft %>
  <%= f.label :draft %>

  <br />
  <%= f.submit "Create post", class: 'button radius info' %>
<% end %>

app/views/posts/index.html.erb
<div class="row">
  <div class="small-9 columns">
	<%= render @posts %>
  </div>
  <div class='small-3 columns'>
	<div class='panel radius'>
	  <% @tags.each do |tag_name| %>
		<h4>
		  <a href='#'><%= tag_name.title %></a>
		</h4>
	  <% end %>
	</div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="small-12 columns">
	<h4 class="text-info">Create new post</h4>
	<%= render 'post_form' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="small-12 columns">
	<div class="post-title">
	  <h1 class="text-info">
		<%= @post.title %>
	  </h1>
	  <small>
		<span class='glyphicon glyphicon-time'></span> <%= @post.created_at.strftime("%A, %d %b %Y %l:%M %p")%>
	  </small>
	</div>

	<div class="post-content">
	  <%=raw @post.body %>
	</div>
	<%= @post.tag_list %>
  </div>
</div>

app/views/shared/_flash.html.erb
<div class="row">
  <div class="small-12 columns">
	<% flash.each do |message_type, message| %>
	  <div data-alert class="alert-box <%= message_type %> radius">
		<%= message %>
		<a href="#" class="close">&times;</a>
	  </div>
	<% end %>
  </div>
</div>

app/views/static_pages/about.html.erb
<h4>About me</h4>

app/views/static_pages/contact.html.erb
<h4>Contact me</h4>

app/views/static_pages/home.html.erb
<div class="row">
  <div class='welcome'>
	<div class='small-9 columns'>
	  <div class="panel radius">
		<h4 class='text-info'>
		  <span class="label custom-label">
			<span class='glyphicon glyphicon-pencil'></span>
			My personal blog
		  </span>
		</h4>
	  </div>
	</div>
	<div class='small-3 columns'>
	  <h5 class='text-info'>Sections</h5>
	</div>
  </div>
</div>
<div class="row">
  <div class='small-9 columns'>
	<div class="panel radius">
	  <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
	  <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
	  <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
	</div>
  </div>


  <div class='small-3 columns'>
	<div class="panel radius white-bg">
	  <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
	</div>
	<div class="panel radius">
	  <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
	</div>
  </div>
</div>